### ISSUE TITLE
How to test validation errors?

### ISSUE THREAD

**Issue by skywickenden** [zth/graphql-query-test-mock#10]
Enjoying the library so far but have hit a road bump when I create a mock which expects a validation error.

Firstly, the error object in the response seems to be completely ignored if status code is not set. As I understand, it is perfectly valid for a graphql server to return an error with a 200 status code - eg a field validation error. In this case relay's `onCompleted: (response, errors)` has null for the error.

relay code:

    const mutation = graphql`
    mutation FooEditMutation(
      $id: ID!,
      $foo: String!
    ){
      editFoo(id: $id, foo: $foo) {
        id
        foo
      }
    }`;

    const variables = {
      id: props.foo.id,
      foo: foo
    };

    commitMutation(environment, {
      mutation,
      variables,
      updater: (store) => {
        console.log("updater running");
        // ...
      },
      onCompleted: (response, errors) => {
        console.log("errors is null");
      },
      onError: error => {throw new Error(error)}
    });

test:

    queryMock.mockQuery({
      name: "FooEditMutation",
      variables: {
        id :"5d07e9310960ad00277ce5d1",
        foo: ""
      },
      data: {
        editFoo: null
      },
      error: {
        errors: [
          {
            message: 'Validation failed: name: Path `foo` is required.',
            locations: [
              {
                line: 7,
                column: 3
              }
            ],
            path: [
              'editFoo'
            ]
          }
        ],
      }
    });  
    fireEvent.change(inputFoo, { target: { value: "" } });
    fireEvent.click(submitFooButton);  
    await wait(() => {
      getByText("Foo is a required field");
    });

After hitting this problem I've been experimenting with different status code and error responses and I can't find one that doesn't throw some kind of error or warning. If I set `status: 401` in the above then I get 

    console.error relay-environment.js:21
      fetch error {
        errors: [
          {
            message: 'Validation failed: name: Path `foo` is required.',
            locations: [Array],
            path: [Array]
          }
        ]
      }

    ● Edit Foo module › Checks an edited foo shows an error if the foo field is empty

    Failed: "Error: TypeError: Cannot read property 'data' of undefined"

      at Env.fail (node_modules/jest-jasmine2/build/jasmine/Env.js:775:61)
      at node_modules/relay-runtime/lib/RelayObservable.js:641:7
      at Object.error (node_modules/relay-runtime/lib/RelayObservable.js:584:11)
      at Object.next (node_modules/relay-runtime/lib/RelayModernQueryExecutor.js:96:16)
      at Object.next (node_modules/relay-runtime/lib/RelayObservable.js:565:20)
      at node_modules/relay-runtime/lib/RelayObservable.js:482:12

The relay `updater` and `onComplete` callbacks are never reached. I've tried shaping the mock in various ways and I can't seem to get it to work. What am I doing wrong?

**Comment by zth** [comment]
Hello!

Nice catch, that functionality was simply missing. Like you noticed, using `error` is just for actual server errors, and therefore has no effect unless you set a status `>= 400`. 

I've added a new prop, `graphqlErrors` that takes an array of errors and returns it according to the GraphQL spec. I released `0.12.0` with those changes. Could you upgrade to that, try that prop out and get back to me here?

You can also look at the test I added for your case: https://github.com/zth/graphql-query-test-mock/blob/48dd1d59f680459e19526d74f4c7cbf594ca7c93/__tests__/queryMock-tests.js#L513

**Comment by skywickenden** [comment]
Thank you. Works great!
