### ISSUE TITLE
New dependency on "babel-polyfill"

### ISSUE THREAD

**Issue by jnak** [zth/graphql-query-test-mock#7]
Hey @zth,

A dependency on "babel-polyfill" was introduced by commit https://github.com/zth/graphql-query-test-mock/commit/99cf4837247ffa529747154f501c62b58878d1c4 because it uses async / await. Babel currently transpiles all +ES2015 syntax because the .babelrc does not specify a node target.

I think we have 2 main options here:
1. Add a step to the "setup" section in README about ["babel-polyfill"](https://babeljs.io/docs/en/babel-polyfill).
2. Set the Node target to +8 since Node 8 has native support for natively async / await. 

My preference would be option 2. because Node 7 is no longer supported and Node 6 will be retired in April (see the [release schedule](https://github.com/nodejs/Release)). Given this is a very young library with few users and targets an audience that uses GraphQL, I have a hunch that dropping support for Node <8 may not impact anyone. Here is what the change would look like: https://github.com/jnak/graphql-query-test-mock/commit/c5b7d46d6801f6c24564d4c0f124937b50b6e140

Let me know if I should send a PR.

Cheers,
J

**Comment by zth** [comment]
I agree, option 2 feels better. Please do send a PR and we'll push a new version. I'll go ahead and add a note to the README just in case too. Good catch, thanks for your work!

**Comment by jnak** [comment]
There you go: https://github.com/zth/graphql-query-test-mock/pull/8 It may make sense to release it as 0.11.0 in case someone was using this library on Node <8.

J

**Comment by zth** [comment]
Thank you @jnak, great stuff! I just published `0.11.0` with the changes.
